[package]
name = "caudal"
description = "Caudal media server binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
caudal-core.workspace = true
caudal-rtmp.workspace = true
caudal-hls.workspace = true
caudal-srt.workspace = true
caudal-ui.workspace = true
caudal-tls.workspace = true
caudal-auth.workspace = true
caudal-webrtc.workspace = true
caudal-moq.workspace = true
caudal-record.workspace = true
caudal-rtsp.workspace = true
caudal-channel.workspace = true
caudal-transcode.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
toml = "1.1.6"
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }

[dev-dependencies]
ureq = { version = "3", default-features = false }
tempfile = "3"
jsonwebtoken = { version = "11", default-features = false, features = ["rust_crypto"] }
rcgen = "0.14"
serde_json.workspace = true
tower = { version = "0.5", features = ["util"] }
