[package]
name = "caudal-hls"
description = "LL-HLS / CMAF output for Caudal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
caudal-core.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
