[package]
name = "caudal-record"
description = "Recording, VOD and clips for Caudal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
caudal-core.workspace = true
caudal-cmaf.workspace = true
axum.workspace = true
tokio.workspace = true
tracing.workspace = true
