[package]
name = "caudal-transcode"
description = "Transcoding and ABR ladders for Caudal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
caudal-core.workspace = true
caudal-ts.workspace = true
tokio.workspace = true
tracing.workspace = true
