apiVersion: v2
name: caudal
description: Caudal media server (RTMP, LL-HLS, SRT, WebRTC/WHIP/WHEP, MoQ)
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/Saul-Punybz/caudal
sources:
  - https://github.com/Saul-Punybz/caudal
keywords:
  - streaming
  - rtmp
  - hls
  - webrtc
  - srt
  - media-server
maintainers:
  - name: Saul-Punybz
