[package]
name = "caudal-rtsp"
description = "RTSP for Caudal: pull IP cameras in, serve streams out"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
caudal-core.workspace = true
tokio.workspace = true
tracing.workspace = true
bytes.workspace = true
futures = "0.3"
url = "2"
rand = "0.8"
base64 = "0.22"
retina = "0.4.13"
rtsp-types = "0.1.3"
sdp-types = "0.2.0"
scuffle-h264 = "0.2.2"
scuffle-h265 = "0.2.2"

[dev-dependencies]
mp4-atom = "0.15.0"
