// Generates Caudal's Material 3 color tokens from the three brand colors,
// using Google's material-color-utilities (the engine behind the Material
// Theme Builder). Output: tokens.css (light + dark, CSS custom properties
// named after M3 roles) and tokens.json. Run: npm run build
import fs from 'node:fs';
import {
  argbFromHex, hexFromArgb, Hct, TonalPalette, DynamicScheme, Variant,
  MaterialDynamicColors, Contrast,
} from '@material/material-color-utilities';

export const BRAND = {
  orange: '#F54F1B',      // primary: action, live, focus
  spaceCadet: '#1E223D',  // secondary + neutrals: structure, dark surfaces
  gargoyleGas: '#E6D5B7', // tertiary: warm accents, light surfaces
};

const hct = (hex) => Hct.fromInt(argbFromHex(hex));
const orange = hct(BRAND.orange);
const cadet = hct(BRAND.spaceCadet);
const gargoyle = hct(BRAND.gargoyleGas);

// FIDELITY keeps the primary container on the brand orange (dark: #ff5723 for
// #F54F1B) but pulls tertiary into a muddy brown; TONAL_SPOT keeps tertiary
// on Gargoyle Gas (light container #f2e0c2). Tertiary roles come from
// TONAL_SPOT, everything else from FIDELITY. Each role group is computed with
// its own contrast guarantees, and the report below checks every text pair.
function scheme(isDark, variant = Variant.FIDELITY) {
  return new DynamicScheme({
    sourceColorHct: orange,
    variant,
    contrastLevel: 0,
    isDark,
    primaryPalette: TonalPalette.fromHct(orange),
    secondaryPalette: TonalPalette.fromHct(cadet),
    tertiaryPalette: TonalPalette.fromHct(gargoyle),
    // Neutrals carry Space Cadet's blue hue so every surface belongs to the brand.
    // Chroma 14 keeps dark surfaces visibly Space Cadet blue (#1d1f2e) rather than gray.
    neutralPalette: TonalPalette.fromHueAndChroma(cadet.hue, 14),
    neutralVariantPalette: TonalPalette.fromHueAndChroma(cadet.hue, 18),
  });
}

const ROLES = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'background', 'onBackground',
  'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'surfaceDim', 'surfaceBright',
  'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer',
  'surfaceContainerHigh', 'surfaceContainerHighest',
  'outline', 'outlineVariant', 'shadow', 'scrim',
  'inverseSurface', 'inverseOnSurface', 'inversePrimary',
];

const mdc = new MaterialDynamicColors();
function roles(s) {
  const out = {};
  for (const r of ROLES) {
    const dc = typeof mdc[r] === 'function' ? mdc[r]() : MaterialDynamicColors[r];
    out[r] = hexFromArgb(dc.getArgb(s));
  }
  return out;
}

const kebab = (k) => k.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());
const block = (sel, r) => `${sel} {\n${Object.entries(r).map(([k, v]) => `  --md-sys-color-${kebab(k)}: ${v};`).join('\n')}\n}\n`;

const TERTIARY = ['tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer'];
function build(isDark) {
  const base = roles(scheme(isDark));
  const spot = roles(scheme(isDark, Variant.TONAL_SPOT));
  for (const r of TERTIARY) base[r] = spot[r];
  return base;
}
const light = build(false);
const dark = build(true);

const css = `/* Generated by ui/theme/generate.mjs from the Caudal brand palette. Do not edit by hand. */
:root {
  --md-ref-brand-orange: ${BRAND.orange};
  --md-ref-brand-space-cadet: ${BRAND.spaceCadet};
  --md-ref-brand-gargoyle-gas: ${BRAND.gargoyleGas};
}
${block(':root, :root[data-theme="light"]', light)}
@media (prefers-color-scheme: dark) {
${block('  :root:not([data-theme="light"])', dark).replace(/^/gm, '  ').trimEnd()}
}
${block(':root[data-theme="dark"]', dark)}`;
fs.writeFileSync('tokens.css', css);
fs.writeFileSync('tokens.json', JSON.stringify({ brand: BRAND, light, dark }, null, 2) + '\n');

// Contrast report for the pairs the UI actually uses (WCAG: 4.5 text, 3 large/UI).
const ratio = (a, b) => Contrast.ratioOfTones(Hct.fromInt(argbFromHex(a)).tone, Hct.fromInt(argbFromHex(b)).tone);
const pairs = (r) => [
  ['onPrimary / primary', r.onPrimary, r.primary],
  ['onPrimaryContainer / primaryContainer', r.onPrimaryContainer, r.primaryContainer],
  ['onSurface / surface', r.onSurface, r.surface],
  ['onSurfaceVariant / surfaceContainer', r.onSurfaceVariant, r.surfaceContainer],
  ['primary / surface', r.primary, r.surface],
  ['onTertiaryContainer / tertiaryContainer', r.onTertiaryContainer, r.tertiaryContainer],
  ['onTertiary / tertiary', r.onTertiary, r.tertiary],
  ['onSecondaryContainer / secondaryContainer', r.onSecondaryContainer, r.secondaryContainer],
  ['onError / error', r.onError, r.error],
];
for (const [name, r] of [['light', light], ['dark', dark]]) {
  console.log(`\n${name}:  primary ${r.primary}  primaryContainer ${r.primaryContainer}  secondary ${r.secondary}  tertiaryContainer ${r.tertiaryContainer}  surface ${r.surface}  surfaceContainer ${r.surfaceContainer}`);
  for (const [n, a, b] of pairs(r)) {
    const c = ratio(a, b);
    console.log(`  ${c >= 4.5 ? 'AA ' : c >= 3 ? 'AA-large' : 'FAIL'}  ${c.toFixed(2)}  ${n}`);
  }
}
console.log('\nbrand tones: orange', orange.tone.toFixed(1), ' spaceCadet', cadet.tone.toFixed(1), ' gargoyleGas', gargoyle.tone.toFixed(1));
