{{- include "caudal.checkAdmin" . -}}
{{- if and .Values.admin.enabled .Values.admin.passwordHash (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "caudal.adminSecretName" . }}
  labels:
    {{- include "caudal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "caudal.adminSecretKey" . }}: {{ .Values.admin.passwordHash | quote }}
{{- end }}
